#!/usr/bin/env node

var util = require('util'),
    hooker = require('./hookobj.js'),
    forever = require('forever'),
    os = require('os');

var path = require('path');
var fs = require('fs');
var log_path = __dirname + '/log';
var logger = require('tracer').dailyfile({root:log_path, format : "{{timestamp}} <{{title}}> {{message}}", dateformat : "HH:MM:ss"});
if (!path.existsSync(log_path)) {
	fs.mkdirSync(log_path, 0755);
}

var
    master_host = "127.0.0.1:8080",
    cpu_nums = os.cpus().length,
    script = __filename + '.js',
    childs = [],
    target;

var stdout = process.stdout;
var stderr = process.stderr;
hooker(stdout);
hooker(stderr);
stdout.hook('write', function(string, encoding, fd, write) {
    logger.log(string);
});
stderr.hook('write', function(string, encoding, fd, write) {
    logger.debug(string);
});

for (var i=0; i<cpu_nums; i++) {
	target = new (forever.Monitor)(script, { 'options': [ "--host", master_host] });

	target.start();
	childs.push(target);
	logger.log('Forever process running ' + script + ' ' + childs.length);
}



