#!/usr/bin/env node

var util = require('util'),
    forever = require('forever'),
    os = require('os');

var logger = require('tracer').dailyfile({root:'./log', format : "{{timestamp}} <{{title}}> {{message}}", dateformat : "HH:MM:ss"});

var
    master_host = "127.0.0.1:8080",
    cpu_nums = os.cpus().length,
    script = __filename + '.js',
    childs = [],
    target;

for (var i=0; i<cpu_nums*3; i++) {
	target = new (forever.Monitor)(script, { 'options': [ "--host", master_host] });

	target.stdout.on('data', function (data) {
		logger.log(data);
	});

	target.stderr.on('data', function (data) {
		logger.debug(data);
	});

	target.on('exit', function (code) {
		logger.log('Child process exited with code: ' + code);
	});

	target.start();
	childs.push(target);
	logger.log('Forever process running ' + script + ' ' + childs.length);
}

